export const SCROLL_INGREDIENTS_BUN = 'SCROLL_INGREDIENTS_BUN';

export const SCROLL_INGREDIENTS_SAUCES = 'SCROLL_INGREDIENTS_SAUCES';

export const SCROLL_INGREDIENTS_MAIN = 'SCROLL_INGREDIENTS_MAIN';